apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubeflow-notebook
  namespace: argocd
spec:
  project: default
  source:
    repoURL: {{ .Values.repoUrl }}
    targetRevision: {{ .Values.targetRevision }}
    path: infra/manifests/helm/notebook
    helm:
      values: |
        aws:
          region: {{ .Values.region }}
        ngc:
          secretName: {{.Values.ngcSecretName}}
          secretProperty: api-key
  destination:
    server: https://kubernetes.default.svc
    namespace: {{ .Values.namespace }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
